### ISSUE TITLE
Fix heroku warnings

### ISSUE THREAD

**Issue by MatheusRich** [dontfile/dontfile#32]
- [x] [1](https://devcenter.heroku.com/articles/ruby-versions)
![image](https://user-images.githubusercontent.com/20938712/39684324-73894d48-5191-11e8-8406-fd60025d878a.png)

- [ ] [2](https://devcenter.heroku.com/articles/active-storage-on-heroku)
![image](https://user-images.githubusercontent.com/20938712/39684331-8814f578-5191-11e8-8463-8ba7ee8f7a94.png)

- [x] [3](https://devcenter.heroku.com/articles/active-storage-on-heroku)
![image](https://user-images.githubusercontent.com/20938712/39684373-bb8c59d2-5191-11e8-8a1a-b577a8e9ca7d.png)

 - [ ] [4](https://devcenter.heroku.com/articles/ruby-default-web-server)
![image](https://user-images.githubusercontent.com/20938712/39684379-c9a187a4-5191-11e8-9485-958352078a6e.png)

**Comment by MatheusRich** [comment]
I'll work on this to provide a fully reliable storage on production. I think in the v1.3.0 it will be done!

**Comment by alaxalves** [comment]
Hey @MatheusRich regarding [this](https://user-images.githubusercontent.com/20938712/39684379-c9a187a4-5191-11e8-9485-958352078a6e.png). Actually this is not a real issue, it just says that you're not using [Foreman gem](https://github.com/ddollar/foreman), and for Dontfile, Foreman is not actually needed since we don't need to run two or more process at once, such as running Sidekiq and Puma server for example.
